# Generated by Django 5.1.1 on 2024-10-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('company_name', models.CharField(max_length=255)),
                ('price_band', models.CharField(max_length=100)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('issue_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('issue_type', models.CharField(max_length=100)),
                ('listing_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('ipo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rhp_pdf', models.FileField(upload_to='rhp_pdfs/')),
                ('drhp_pdf', models.FileField(upload_to='drhp_pdfs/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
